CREATE DATABASE Orca_db;
use Orca_db;

CREATE TABLE Properties (
    propertyID INT AUTO_INCREMENT PRIMARY KEY,
    Rent VARCHAR(255) NOT NULL,
    Bills VARCHAR(255) NOT NULL,
    Maintenance VARCHAR(255) NOT NULL,
    Event VARCHAR(255) NOT NULL,
    ERC VARCHAR(255) NOT NULL,
    managerID INT FOREIGN KEY REFERENCES Managers(managerID) NOT NULL
);

CREATE TABLE Resident (
    residentID INT AUTO_INCREMENT PRIMARY KEY,
    wallet VARCHAR(255) NOT NULL, 
);

CREATE TABLE Managers (
    managerID INT AUTO_INCREMENT PRIMARY KEY,
    wallet VARCHAR(255) NOT NULL,
);